version: '3.9'

services:
  db:
    image: postgres:16
    container_name: smartdesk-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: smartdesk
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
    container_name: smartdesk-backend
    restart: always
    depends_on:
      - db
    ports:
      - "4000:4000"
    volumes:
      - ./backend:/app
    environment:
      PORT: 4000
      ACCESS_TOKEN: secret_access_token
      REFRESH_TOKEN: secret_refresh_token
      DATABASE_URL: postgres://postgres:password@db:5432/smartdesk
    command: npm run dev


volumes:
  postgres-data: